trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - 'Resources/IaC-Modules/**'

variables: 
- name: ServiceConnectionName
  value: '....'
- name: AzureResourceGroupName
  value: devopsworkshop2023
- name: AzureRegion
  value: westeurope
- name: TemplateSpecName
  value: app-service-containers


pool:
  vmImage: ubuntu-latest

stages:
- stage: Publish
  jobs:
  - job: Publish
    steps:
      - task: AzureCLI@2
        name: Publish
        displayName: Publish template spec
        inputs:
          azureSubscription: $(ServiceConnectionName)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az ts create \
              --resource-group $(AzureResourceGroupName) \
              --name $(TemplateSpecName) \
              --version $(Build.BuildNumber) \
              --template-file Resources/IaC-Modules/main.bicep \
              --location $(AzureRegion) \
              --yes
