variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
- name: BuildParameters.TestProjects
  value: '**/*[Tt]ests/*.csproj'
- name: BuildConfiguration
  value: 'Debug'

trigger:
  branches:
    include:
    - refs/heads/main
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: AJRun
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      version: '7.x'
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: $(BuildParameters.RestoreBuildProjects)
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration)
  # - task: DotNetCoreCLI@2
  #   displayName: Test
  #   inputs:
  #     command: test
  #     projects: $(BuildParameters.TestProjects)
  #     arguments: --configuration $(BuildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      projects: $(BuildParameters.RestoreBuildProjects)
      arguments: --configuration $(BuildConfiguration) --output $(System.DefaultWorkingDirectory)/PublishedWebApp
      zipAfterPublish: false
  # - task: Bash@3
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       ls -liat
  #       ls -liat Resources/Application/src/RazorPagesTestTemplate
  #       cd PublishedWebApp
  #       ls -liat RazorPagesTestSample
  - task: Docker@2
    inputs:
      containerRegistry: 'acrworkshop'
      repository: 'myDevOpsApp'
      command: 'buildAndPush'
  #     buildContext: '$(System.DefaultWorkingDirectory)/PublishedWebApp'
